SELECT * FROM movie_companies AS mc,title AS t,movie_info_idx AS mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=112 AND mc.company_type_id=2;
SELECT * FROM movie_companies AS mc,title AS t,movie_info_idx AS mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=113 AND mc.company_type_id=2 AND t.production_year>2005 AND t.production_year<2010;
SELECT * FROM movie_companies AS mc,title AS t,movie_info_idx AS mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=112 AND mc.company_type_id=2 AND t.production_year>2010;
SELECT * FROM movie_companies AS mc,title AS t,movie_info_idx AS mi_idx WHERE t.id=mc.movie_id AND t.id=mi_idx.movie_id AND mi_idx.info_type_id=113 AND mc.company_type_id=2 AND t.production_year>2000;
SELECT * FROM movie_companies AS mc,title AS t,movie_keyword AS mk WHERE t.id=mc.movie_id AND t.id=mk.movie_id AND mk.keyword_id=117;
SELECT * FROM title AS t,movie_info AS mi,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.production_year>2005;
SELECT * FROM title AS t,movie_info AS mi,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.production_year>2010;
SELECT * FROM title AS t,movie_info AS mi,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.production_year>1990;
SELECT * FROM title AS t,movie_info_idx AS mi_idx,movie_keyword AS mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>2005 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info_idx AS mi_idx,movie_keyword AS mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>2010 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info_idx AS mi_idx,movie_keyword AS mk WHERE t.id=mi_idx.movie_id AND t.id=mk.movie_id AND t.production_year>1990 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.production_year>2005 AND mc.company_type_id=2;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.production_year>2010 AND mc.company_type_id=2;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.production_year>1990 AND mc.company_type_id=2;
SELECT * FROM movie_keyword AS mk,title AS t,cast_info AS ci WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.production_year>2010 AND mk.keyword_id=8200;
SELECT * FROM movie_keyword AS mk,title AS t,cast_info AS ci WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.production_year>2014;
SELECT * FROM movie_keyword AS mk,title AS t,cast_info AS ci WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.production_year>2014 AND mk.keyword_id=8200;
SELECT * FROM movie_keyword AS mk,title AS t,cast_info AS ci WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.production_year>2000 AND mk.keyword_id=8200;
SELECT * FROM movie_keyword AS mk,title AS t,cast_info AS ci WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.production_year>2000;
SELECT * FROM cast_info AS ci,title AS t WHERE t.id=ci.movie_id AND t.production_year>1980 AND t.production_year<1995;
SELECT * FROM cast_info AS ci,title AS t WHERE t.id=ci.movie_id AND t.production_year>1980 AND t.production_year<1984;
SELECT * FROM cast_info AS ci,title AS t WHERE t.id=ci.movie_id AND t.production_year>1980 AND t.production_year<2010;
SELECT * FROM cast_info AS ci,title AS t,movie_companies AS mc WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND ci.role_id=2;
SELECT * FROM cast_info AS ci,title AS t,movie_companies AS mc WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND ci.role_id=4;
SELECT * FROM cast_info AS ci,title AS t,movie_companies AS mc WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND ci.role_id=7;
SELECT * FROM cast_info AS ci,title AS t,movie_companies AS mc WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.production_year>2005 AND t.production_year<2015 AND ci.role_id=2;
SELECT * FROM cast_info AS ci,title AS t,movie_companies AS mc WHERE t.id=ci.movie_id AND t.id=mc.movie_id AND t.production_year>2007 AND t.production_year<2010 AND ci.role_id=2;
SELECT * FROM title AS t,cast_info AS ci,movie_companies AS mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year>2005 AND ci.role_id=1;
SELECT * FROM title AS t,cast_info AS ci,movie_companies AS mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year>2010 AND ci.role_id=1;
SELECT * FROM title AS t,cast_info AS ci,movie_companies AS mc WHERE t.id=mc.movie_id AND t.id=ci.movie_id AND t.production_year>1990;
SELECT * FROM title AS t,movie_keyword AS mk,movie_companies AS mc WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id=398 AND mc.company_type_id=2 AND t.production_year>1950 AND t.production_year<2000;
SELECT * FROM title AS t,movie_keyword AS mk,movie_companies AS mc WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id=398 AND mc.company_type_id=2;
SELECT * FROM title AS t,movie_keyword AS mk,movie_companies AS mc WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.production_year>1950;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=101 AND mi.info_type_id=3 AND t.production_year>2005 AND t.production_year<2008 AND mc.company_type_id=2;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=113 AND mi.info_type_id=105;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND mi_idx.info_type_id=101 AND mi.info_type_id=3 AND t.production_year>2000 AND t.production_year<2010 AND mc.company_type_id=2;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,movie_info_idx AS mi_idx WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=1 AND mc.company_type_id=2 AND mi_idx.info_type_id=101 AND mi.info_type_id=16;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2010 AND t.kind_id=1 AND mi.info_type_id=8 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.kind_id=1 AND mi.info_type_id=8 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2005 AND mi.info_type_id=8 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mi.info_type_id=16 AND t.production_year>2000;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mi.info_type_id=16 AND t.production_year>2005 AND t.production_year<2010;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mi.info_type_id=16 AND t.production_year>1990;
SELECT * FROM cast_info AS ci,title AS t,movie_keyword AS mk,movie_companies AS mc WHERE t.id=ci.movie_id AND t.id=mk.movie_id AND t.id=mc.movie_id AND mk.keyword_id=117;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,cast_info AS ci WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND mi.info_type_id=105 AND mi_idx.info_type_id=100;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,cast_info AS ci WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND mi.info_type_id=3 AND mi_idx.info_type_id=101 AND t.production_year>2008 AND t.production_year<2014;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,cast_info AS ci WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND mi.info_type_id=3 AND mi_idx.info_type_id=100;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2 AND mi.info_type_id=16 AND t.production_year>2005 AND t.production_year<2009;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2 AND mi.info_type_id=16;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND ci.role_id=2 AND mi.info_type_id=16 AND t.production_year>2000;
SELECT * FROM title AS t,cast_info AS ci,movie_keyword AS mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.production_year>1950 AND t.kind_id=1;
SELECT * FROM title AS t,cast_info AS ci,movie_keyword AS mk WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.production_year>2000 AND t.kind_id=1;
SELECT * FROM title AS t,movie_keyword AS mk,movie_companies AS mc,movie_info AS mi WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mk.keyword_id=398 AND mc.company_type_id=2 AND t.production_year>1950 AND t.production_year<2000;
SELECT * FROM title AS t,movie_keyword AS mk,movie_companies AS mc,movie_info AS mi WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mk.keyword_id=398 AND mc.company_type_id=2 AND t.production_year>2000 AND t.production_year<2010;
SELECT * FROM title AS t,movie_keyword AS mk,movie_companies AS mc,movie_info AS mi WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mk.keyword_id=398 AND mc.company_type_id=2 AND t.production_year>1950 AND t.production_year<2010;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_keyword AS mk,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.production_year>2008 AND mi.info_type_id=8 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_keyword AS mk,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.production_year>2009 AND mi.info_type_id=8 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND ci.role_id=2 AND mi.info_type_id=16 AND t.production_year>2010;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND ci.role_id=2 AND mi.info_type_id=16 AND t.production_year>2010 AND mc.company_id=22956;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND ci.role_id=2 AND mi.info_type_id=16 AND t.production_year>2000;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mi.info_type_id=3 AND mi_idx.info_type_id=100;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mi.info_type_id=3 AND mi_idx.info_type_id=100 AND t.production_year>2010;
SELECT * FROM title AS t,cast_info AS ci,movie_keyword AS mk,movie_info_idx AS mi_idx WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2000 AND t.kind_id=1 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,cast_info AS ci,movie_keyword AS mk,movie_info_idx AS mi_idx WHERE t.id=mk.movie_id AND t.id=ci.movie_id AND t.id=mi_idx.movie_id AND t.production_year>2005 AND t.kind_id=1 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_keyword AS mk,movie_companies AS mc,movie_info AS mi WHERE t.id=mk.movie_id AND t.id=mc.movie_id AND t.id=mi.movie_id AND mk.keyword_id=398 AND mc.company_type_id=2 AND t.production_year=1998;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_keyword AS mk,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.production_year>2000 AND mi.info_type_id=8 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,movie_keyword AS mk,movie_companies AS mc WHERE t.id=mi.movie_id AND t.id=mk.movie_id AND t.id=mi_idx.movie_id AND t.id=mc.movie_id AND t.production_year>2005 AND mi.info_type_id=8 AND mi_idx.info_type_id=101;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND ci.role_id=2 AND mi.info_type_id=16 AND t.production_year>2000 AND t.production_year<2010 AND mk.keyword_id=7084;
SELECT * FROM title AS t,movie_info AS mi,movie_companies AS mc,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mc.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND ci.role_id=2 AND mi.info_type_id=16 AND t.production_year>2000 AND t.production_year<2005 AND mk.keyword_id=7084;
SELECT * FROM title AS t,movie_info AS mi,movie_info_idx AS mi_idx,cast_info AS ci,movie_keyword AS mk WHERE t.id=mi.movie_id AND t.id=mi_idx.movie_id AND t.id=ci.movie_id AND t.id=mk.movie_id AND mi.info_type_id=3 AND mi_idx.info_type_id=100 AND t.production_year>2000;
